In [37]:
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from cossim import build_cossim
import numpy as np
from numpy import linalg as LA
import re

In [38]:
lyrics = pickle.load(open("broadway_lyrics_v5.pkl", "rb"))

In [39]:
lyrics.keys()

dict_keys(['Babes In Arms', 'Matilda', '70, Girls, 70', 'Hamilton', "Finian's Rainbow", 'High Society', 'American Idiot', 'Sunset Boulevard', 'Jekyll & Hyde', 'High School Musical On Stage', "Li'l Abner", 'Hedwig And The Angry Inch', 'Bring It On', 'So Long, 174th Street', 'Little Mary Sunshine', 'Scrooge', 'Jacques Brel Is Alive and Well and Living in Paris', 'See What I Wanna See', 'Nice Work If You Can Get It', 'Drowsy Chaperone, The', 'Seven Brides For Seven Brothers', 'Boy Friend, The', 'Across the Universe', 'Make Me A Song', 'Spamalot', 'Wizard Of Oz, The', 'Evita', 'Bronx Tale', 'In the Heights', 'Take Flight', 'Bajour', 'Title Of Show', 'I Sing', 'I Love You Because', 'Milk And Honey', 'Can-Can', 'Anna Karenina', 'How the Grinch Stole Christmas', 'Pajama Game, The', 'Frankenstein: A New Musical', 'Gone Missing', 'Jane Eyre', 'Urinetown', 'Colma', 'We Will Rock You', 'Bullets Over Broadway', 'Starlight Express', '42nd Street', 'Priscilla: Queen of the Desert', 'Bright Lights, B

In [40]:
lyrics["Mamma Mia!"]

{'composer': 'Benny Andersson and Bjorn Ulvaeus.',
 'currently_playing': False,
 'description': "ABBA's songs were so popular that the idea of creating a musical based on them was resting on the surface. But it came to mind only to Judy Kreimer. Thanks to the efforts of the discerning producer, the musical “Mamma Mia” was born. Known tunes included in the golden fund of world music collection. Using them for staging illustrations was a great idea. No matter in whose performance sounded songs of the legendary band – they continued to be provocative and inflaming. Lyrics of Swedish composers in the performance perfectly complement its storyline. They contain simple aspirations of ordinary people. It is due to this compositions, the histrionics became close to almost all the spectators. Experiences of Sophie and Donna perfectly transferred in songs, performed by women at different points in their lives. Wonderfully arranged dance numbers enable the public to immerse themselves in the hist

In [41]:
# get TF-IDF of lyrics

d = {}
for show in lyrics:
    S = ""
    for line in lyrics[show]["lyrics"]:
        S += " " + line
    d[show] = S
    
tfidf_vec = TfidfVectorizer(max_features = 6000, stop_words = "english", max_df = 0.85, min_df = 10, norm = "l2")
doc_by_vocab = tfidf_vec.fit_transform([d[i] for i in d]).toarray()
index_to_vocab = {i:v for i, v in enumerate(tfidf_vec.get_feature_names())}

In [42]:
musical_name_to_index = {musical:index for index, musical in enumerate(lyrics.keys())}

In [43]:
doc_by_vocab[214]

array([0., 0., 0., ..., 0., 0., 0.])

In [44]:
musical_name_to_index["Mamma Mia!"]

398

In [45]:
normboy = np.apply_along_axis(LA.norm,1,doc_by_vocab)

In [46]:
musical_index_to_name = {value:key for key,value in musical_name_to_index.items()}

In [47]:
cosmat = build_cossim(doc_by_vocab)

C:\Users\AChatt10\OneDrive\Arjun\School\2018-19 (Sem2)\CS 4300\cs4300sp2019-jp2254-nmd65-bdg74-ac2582-srm276\cossim.py:17: RuntimeWarning: invalid value encountered in true_divide
  intermediate = np.divide(dot,norms)
C:\Users\AChatt10\OneDrive\Arjun\School\2018-19 (Sem2)\CS 4300\cs4300sp2019-jp2254-nmd65-bdg74-ac2582-srm276\cossim.py:18: RuntimeWarning: invalid value encountered in true_divide
  sim_mat = np.divide(np.transpose(intermediate),norms)


In [48]:
np.sum(np.isnan(cosmat),axis=1)

array([ 40,  40,  40,  40, 472,  40,  40,  40,  40,  40,  40,  40,  40,
       472, 472,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,
        40,  40,  40, 472,  40,  40,  40,  40,  40, 472,  40,  40,  40,
        40,  40,  40,  40,  40,  40,  40,  40, 472,  40,  40,  40,  40,
        40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,
        40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,
        40,  40,  40,  40,  40,  40,  40,  40,  40, 472,  40,  40, 472,
        40,  40,  40,  40,  40,  40,  40,  40,  40,  40, 472,  40,  40,
        40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,
       472,  40,  40,  40,  40,  40,  40,  40, 472,  40,  40,  40, 472,
        40,  40,  40, 472,  40,  40,  40,  40,  40,  40,  40,  40,  40,
        40,  40,  40,  40,  40, 472,  40,  40, 472,  40, 472,  40,  40,
        40,  40,  40,  40, 472,  40,  40, 472,  40,  40,  40,  40, 472,
        40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  40,  4

In [49]:
musical_index_to_name

{0: 'Babes In Arms',
 1: 'Matilda',
 2: '70, Girls, 70',
 3: 'Hamilton',
 4: "Finian's Rainbow",
 5: 'High Society',
 6: 'American Idiot',
 7: 'Sunset Boulevard',
 8: 'Jekyll & Hyde',
 9: 'High School Musical On Stage',
 10: "Li'l Abner",
 11: 'Hedwig And The Angry Inch',
 12: 'Bring It On',
 13: 'So Long, 174th Street',
 14: 'Little Mary Sunshine',
 15: 'Scrooge',
 16: 'Jacques Brel Is Alive and Well and Living in Paris',
 17: 'See What I Wanna See',
 18: 'Nice Work If You Can Get It',
 19: 'Drowsy Chaperone, The',
 20: 'Seven Brides For Seven Brothers',
 21: 'Boy Friend, The',
 22: 'Across the Universe',
 23: 'Make Me A Song',
 24: 'Spamalot',
 25: 'Wizard Of Oz, The',
 26: 'Evita',
 27: 'Bronx Tale',
 28: 'In the Heights',
 29: 'Take Flight',
 30: 'Bajour',
 31: 'Title Of Show',
 32: 'I Sing',
 33: 'I Love You Because',
 34: 'Milk And Honey',
 35: 'Can-Can',
 36: 'Anna Karenina',
 37: 'How the Grinch Stole Christmas',
 38: 'Pajama Game, The',
 39: 'Frankenstein: A New Musical',
 40:

In [50]:
cosmat

array([[1.        , 0.11718013, 0.06541672, ..., 0.06827179, 0.10211948,
        0.07283828],
       [0.11718013, 1.        , 0.1042975 , ..., 0.06561213, 0.16286545,
        0.14105183],
       [0.06541672, 0.1042975 , 1.        , ..., 0.04585987, 0.09490929,
        0.07965923],
       ...,
       [0.06827179, 0.06561213, 0.04585987, ..., 1.        , 0.07552562,
        0.05377613],
       [0.10211948, 0.16286545, 0.09490929, ..., 0.07552562, 1.        ,
        0.1473648 ],
       [0.07283828, 0.14105183, 0.07965923, ..., 0.05377613, 0.1473648 ,
        1.        ]])

In [51]:
def get_sim(mus_1, mus_2, sim_mat = cosmat, name_to_index = musical_name_to_index):
    ind_1 = name_to_index[mus_1]
    ind_2 = name_to_index[mus_2]
    score = sim_mat[ind_1,ind_2]
    return score

In [52]:
def rank_mus(musical,matrix):
    mus_idx = musical_name_to_index[musical]
    score_list = matrix[mus_idx]
    sorted_i = np.argsort(score_list)[::-1]
    mus_score_list = [(musical_index_to_name[i],score) for i,score in enumerate(score_list)]
#     mus_score_list_sorted = sorted(mus_score_list,key=lambda i: -i[1])
#     print(score_list)
    return np.array(mus_score_list)[sorted_i]

In [53]:
rank_mus("Mamma Mia!",cosmat)

array([["Bring In 'Da Noise, Bring In 'Da Funk", 'nan'],
       ['Do Black Patent Leather Shoes Really Reflect Up?', 'nan'],
       ['Pump Boys And Dinettes', 'nan'],
       ["Singin' In The Rain", 'nan'],
       ['Side Show', 'nan'],
       ['Mr. Mark Twain', 'nan'],
       ['On Your Feet!', 'nan'],
       ['First Date', 'nan'],
       ["Jelly's Last Jam", 'nan'],
       ['How to Succeed in Business Without Really Trying', 'nan'],
       ['Fosse', 'nan'],
       ['Take Flight', 'nan'],
       ['Gentlemen Prefer Blondes', 'nan'],
       ["Kitty's Kisses", 'nan'],
       ['Producers', 'nan'],
       ['Can-Can', 'nan'],
       ['Sunday in the Park With George', 'nan'],
       ["Summer of '42", 'nan'],
       ['Jennie', 'nan'],
       ['Fame Becomes Me', 'nan'],
       ['42nd Street', 'nan'],
       ['Cannibal', 'nan'],
       ['Andrew Lloyd Webber Divas', 'nan'],
       ['Addams Family, The', 'nan'],
       ['Lennon', 'nan'],
       ['Burn The Floor', 'nan'],
       ['Yank!', 'nan'],
   

In [54]:
# composer stuff
for i in lyrics:
    print(lyrics[i]["composer"])

Richard Rodgers.
Tim Minchin
John Kander

Burton Lane
Cole Porter
Green Day
Andrew Lloyd Webber
Frank Wildhorn
Matthew Gerrard, Robbie Nevil, Ray Cham, Greg Cham, Drew Seeley, Randy Petersen, Kevin Quinn, Andy Dodd, Adam Watts, Bryan Louiselle, David N. Lawrence, Faye Greenberg, Jamie Houston
Gene De Paul
Stephen Trask
Amanda Green and Lin-Manuel Miranda
Stan Daniels

Leslie Bricusse
Jacques Brel

George Gershwin
Lisa Lambert & Greg Morrison.
Gene DePaul
Sandy Wilson.
the Beatles
William Finn
John Du Prez, Eric Idle and Neil Innes
Harold Arlen and Herbert Stothart
Andrew Lloyd Webber
Alan Menken
Lin-Manuel Miranda.
David Shire
Walter Marks.
Jeff Bowen

Joshua Salzman.
Jerry Herman
Cole Porter
Daniel Levine
Mel Marvin, Albert Hague
Richard Adler and Jerry Ross
Mark Baron
Michael Friedman
Paul Gordon
Mark Hollmann
H.P. Mendoza
Queen
Various
Andrew Lloyd Webber
Harry Warren
Various

Adam Guettel
Alan Menken.
Cy Coleman.
Music and Lyrics Stephen Sondheim

Jimmy Roberts
Andrew Lloyd Webber


In [55]:
compM = np.zeros([len(lyrics),len(lyrics)])
for mus1 in musical_name_to_index:
    i = musical_name_to_index[mus1]
    comp1 = lyrics[mus1]["composer"]
    if len(comp1) > 0:
        comp1_nop = re.sub(r'[^\w ,]','',comp1)
        for mus2 in musical_name_to_index:
            j = musical_name_to_index[mus2]
            comp2 = lyrics[mus2]["composer"]
            if len(comp2) > 0:
                comp2_nop = re.sub(r'[^\w ,]','',comp2)
                compM[i,j] = (comp1_nop in comp2_nop) or (comp2_nop in comp1_nop)

In [56]:
for i in range(len(compM)):
    print(sum(compM[i,:]))

12.0
2.0
9.0
0.0
2.0
6.0
1.0
15.0
6.0
1.0
1.0
1.0
2.0
1.0
0.0
2.0
1.0
0.0
4.0
1.0
1.0
1.0
1.0
6.0
1.0
1.0
15.0
9.0
2.0
4.0
1.0
1.0
0.0
1.0
7.0
6.0
1.0
2.0
2.0
1.0
1.0
1.0
1.0
1.0
1.0
7.0
15.0
1.0
7.0
0.0
3.0
9.0
8.0
14.0
0.0
2.0
15.0
3.0
2.0
1.0
7.0
2.0
3.0
1.0
1.0
14.0
0.0
2.0
15.0
2.0
1.0
3.0
15.0
1.0
9.0
0.0
1.0
0.0
1.0
0.0
12.0
1.0
2.0
8.0
1.0
12.0
5.0
0.0
1.0
0.0
3.0
3.0
8.0
7.0
1.0
10.0
0.0
1.0
8.0
4.0
5.0
0.0
2.0
1.0
12.0
2.0
1.0
2.0
10.0
1.0
0.0
8.0
0.0
0.0
0.0
1.0
1.0
0.0
6.0
1.0
0.0
1.0
1.0
12.0
6.0
4.0
0.0
1.0
1.0
1.0
2.0
1.0
2.0
1.0
1.0
15.0
0.0
1.0
1.0
0.0
15.0
4.0
1.0
4.0
15.0
1.0
1.0
0.0
10.0
4.0
8.0
0.0
0.0
2.0
4.0
4.0
2.0
1.0
10.0
1.0
3.0
3.0
1.0
1.0
0.0
6.0
4.0
4.0
1.0
6.0
1.0
2.0
2.0
5.0
4.0
9.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
8.0
0.0
5.0
0.0
3.0
1.0
1.0
15.0
1.0
14.0
1.0
1.0
9.0
2.0
0.0
0.0
2.0
9.0
4.0
3.0
4.0
1.0
4.0
1.0
8.0
6.0
1.0
15.0
1.0
1.0
12.0
3.0
9.0
1.0
9.0
1.0
1.0
1.0
0.0
1.0
1.0
8.0
2.0
1.0
1.0
14.0
4.0
2.0
9.0
7.0
3.0
1.0
1.0
0.0
5.0
4.0
12.0
1.0
0.0
9.0
1.

In [57]:
musical_name_to_index

{'110 in the Shade': 90,
 '13': 354,
 '1776': 328,
 '25th Annual Putnam County Spelling Bee': 410,
 '42nd Street': 47,
 '70, Girls, 70': 2,
 '9 to 5': 159,
 'A Day in Hollywood / A Night in the Ukraine': 288,
 'Ace': 258,
 'Across the Universe': 22,
 'Act, The': 467,
 'Addams Family, The': 160,
 'Adding Machine': 277,
 'Adrift In Macao': 453,
 'Adventures of Tom Sawyer, The': 128,
 'Aida': 444,
 "Ain't Misbehavin'": 407,
 "Ain't Too Proud": 191,
 'Aladdin': 231,
 "Alas! Alack! Zorro's Back!": 382,
 'All Shook Up': 353,
 'Allegro': 85,
 'Altar Boyz': 146,
 'American Idiot': 6,
 'American Mall': 446,
 'American in Paris, An': 389,
 'Anastasia': 111,
 'Andrew Lloyd Webber Divas': 400,
 'Anna Karenina': 36,
 'Annie': 100,
 'Annie Get Your Gun': 315,
 'Anyone Can Whistle': 325,
 'Anything Goes': 470,
 'Applause': 284,
 'Apple Tree, The': 334,
 'Ark, The': 445,
 'As Thousands Cheer': 269,
 'Aspects of Love': 190,
 'Assassins': 351,
 'Avenue Q': 305,
 'Babes In Arms': 0,
 'Baby': 154,
 'Bad G

In [60]:
# get TF-IDF of descriptions
    
tfidf_vec2 = TfidfVectorizer(max_features = 6000, stop_words = "english", max_df = 0.85, min_df = 3, norm = "l2")
doc_by_vocab2 = tfidf_vec2.fit_transform([str(lyrics[m]["description"]) for m in lyrics]).toarray()
index_to_vocab2 = {i:v for i, v in enumerate(tfidf_vec2.get_feature_names())}

In [ ]:
cosmat[np.isnan(cosmat)] = 0

In [ ]:
np.savetxt("sim_matrix.csv",cosmat,delimiter=",") #saving the similarity matrix

In [ ]:
import json
json1 = json.dumps(musical_name_to_index) #saving name to index dictionary
f = open("name_to_index.json","w")
f.write(json1)
f.close()
json2 = json.dumps(musical_index_to_name) #saving index to name dictionary
f = open("index_to_name.json","w")
f.write(json2)
f.close()

In [ ]:
np.savetxt("composer_sim.csv",compM,delimiter=",") #saving the composer similarity